name: Publish new minor release

on: workflow_dispatch

jobs:
  dowload_artifact:
    name: Generate and publish new minor release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      checks: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Determine version
        id: version
        uses: zwaldowski/semver-release-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
          bump: minor

      - name: Publish new version
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ steps.version.outputs.version }}

      - name: Update version tag
        uses: zwaldowski/semver-release-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          bump: minor
